FROM java:8
MAINTAINER yangqifang<1114923161@qq.com>
WORKDIR /open/resource/
ADD /target/resource-server-0.0.1-SNAPSHOT.jar /open/resource/
ENTRYPOINT ["java","-jar","resource-server-0.0.1-SNAPSHOT.jar"]
EXPOSE 8765